// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	ratings "mini-project-movie-api/businesses/ratings"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ratingDomain
func (_m *Repository) Create(ratingDomain *ratings.Domain) ratings.Domain {
	ret := _m.Called(ratingDomain)

	var r0 ratings.Domain
	if rf, ok := ret.Get(0).(func(*ratings.Domain) ratings.Domain); ok {
		r0 = rf(ratingDomain)
	} else {
		r0 = ret.Get(0).(ratings.Domain)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id string) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Repository) GetAll() []ratings.Domain {
	ret := _m.Called()

	var r0 []ratings.Domain
	if rf, ok := ret.Get(0).(func() []ratings.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ratings.Domain)
		}
	}

	return r0
}

// GetAvgScore provides a mock function with given fields: movieId
func (_m *Repository) GetAvgScore(movieId string) float64 {
	ret := _m.Called(movieId)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(movieId)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id string) ratings.Domain {
	ret := _m.Called(id)

	var r0 ratings.Domain
	if rf, ok := ret.Get(0).(func(string) ratings.Domain); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(ratings.Domain)
	}

	return r0
}

// GetByMovieID provides a mock function with given fields: movieId
func (_m *Repository) GetByMovieID(movieId string) []ratings.Domain {
	ret := _m.Called(movieId)

	var r0 []ratings.Domain
	if rf, ok := ret.Get(0).(func(string) []ratings.Domain); ok {
		r0 = rf(movieId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ratings.Domain)
		}
	}

	return r0
}

// GetByMovieIdAndUserID provides a mock function with given fields: movieId, userId
func (_m *Repository) GetByMovieIdAndUserID(movieId string, userId string) ratings.Domain {
	ret := _m.Called(movieId, userId)

	var r0 ratings.Domain
	if rf, ok := ret.Get(0).(func(string, string) ratings.Domain); ok {
		r0 = rf(movieId, userId)
	} else {
		r0 = ret.Get(0).(ratings.Domain)
	}

	return r0
}

// GetByUserID provides a mock function with given fields: userId
func (_m *Repository) GetByUserID(userId string) []ratings.Domain {
	ret := _m.Called(userId)

	var r0 []ratings.Domain
	if rf, ok := ret.Get(0).(func(string) []ratings.Domain); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ratings.Domain)
		}
	}

	return r0
}

// Update provides a mock function with given fields: id, ratingDomain
func (_m *Repository) Update(id string, ratingDomain *ratings.Domain) ratings.Domain {
	ret := _m.Called(id, ratingDomain)

	var r0 ratings.Domain
	if rf, ok := ret.Get(0).(func(string, *ratings.Domain) ratings.Domain); ok {
		r0 = rf(id, ratingDomain)
	} else {
		r0 = ret.Get(0).(ratings.Domain)
	}

	return r0
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
